from flask import redirect, url_for, flash, request
from flask_login import current_user
from flask_admin import Admin, AdminIndexView
from flask_admin.contrib.sqla import ModelView
from app import db
from app.models import (
    User, Listing, Order, Transaction, Dispute, 
    Withdrawal, Notification, PriceHistory, Favorite, PriceAlert
)

# --- 🛡️ SECURITY PROTOCOL ---

class GridAdminIndexView(AdminIndexView):
    """Restricts the main admin panel to Super Admins only."""
    def is_accessible(self):
        return current_user.is_authenticated and current_user.is_admin

    def inaccessible_callback(self, name, **kwargs):
        flash("Access Denied: High-level security clearance required.", "danger")
        return redirect(url_for('auth.login', next=request.url))

class SecureModelView(ModelView):
    """Base class for all model views to inherit security logic."""
    def is_accessible(self):
        return current_user.is_authenticated and current_user.is_admin

    def inaccessible_callback(self, name, **kwargs):
        return redirect(url_for('auth.login', next=request.url))

# --- 👥 IDENTITY NODE VIEW ---

class UserModelView(SecureModelView):
    column_list = ('id', 'name', 'email', 'phone', 'is_driver', 'is_verified', 'wallet_balance')
    column_searchable_list = ['name', 'email', 'phone']
    column_filters = ['is_driver', 'is_verified', 'is_admin']
    can_create = False  # Users should register via the main app
    can_edit = True
    can_delete = False  # Prevent accidental wiping of user history

# --- 📦 ASSET NODE VIEW ---

class ListingModelView(SecureModelView):
    # Using 'seller.name' to display human-readable names instead of IDs
    column_list = ('id', 'title', 'price', 'category', 'section', 'state', 'status', 'seller.name')
    column_searchable_list = ['title', 'description']
    column_filters = ['category', 'section', 'state', 'status']

# --- 🤝 HANDSHAKE & ESCROW VIEW ---

class OrderModelView(SecureModelView):
    column_list = ('handshake_id', 'total_price', 'status', 'delivery_status', 'buyer.name', 'driver.name', 'timestamp')
    column_searchable_list = ['handshake_id']
    column_filters = ['status', 'delivery_status']
    can_create = False  # Orders must be generated by user logic

# --- 💸 FINANCIAL & DISPUTE VIEW ---

class WithdrawalModelView(SecureModelView):
    column_list = ('id', 'user.name', 'amount', 'bank_name', 'account_number', 'status', 'request_date')
    column_filters = ['status']
    form_columns = ('status',) # Admin usually just approves/rejects

class DisputeModelView(SecureModelView):
    column_list = ('id', 'order.handshake_id', 'claimant.name', 'reason', 'status', 'created_at')
    column_filters = ['status', 'reason']

# --- 🚀 INITIALIZATION FUNCTION ---

def setup_admin(app):
    """Deploys the Admin Panel to the Flask App."""
    admin = Admin(app, name='FlipTrybe HQ', template_mode='bootstrap4', index_view=GridAdminIndexView())
    
    # Core Nodes
    admin.add_view(UserModelView(User, db.session, name="Identity Nodes"))
    admin.add_view(ListingModelView(Listing, db.session, name="Asset Manifest"))
    
    # Operations
    admin.add_view(OrderModelView(Order, db.session, name="Escrow Handshakes"))
    admin.add_view(WithdrawalModelView(Withdrawal, db.session, name="Liquidity Requests"))
    admin.add_view(DisputeModelView(Dispute, db.session, name="Dispute Terminal"))
    
    # Telemetry (Read-Only/Audit)
    admin.add_view(SecureModelView(Transaction, db.session, category="Audit Logs"))
    admin.add_view(SecureModelView(PriceHistory, db.session, category="Audit Logs"))
    admin.add_view(SecureModelView(Notification, db.session, category="Audit Logs"))
    admin.add_view(SecureModelView(Favorite, db.session, category="User Signals"))
    admin.add_view(SecureModelView(PriceAlert, db.session, category="User Signals"))
    
    return admin