"""Master Sync: Genesis Architecture

Revision ID: 622c53e5e088
Revises: f3a1b2c4d5e6
Create Date: 2026-01-29 09:30:58.763645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622c53e5e088'
down_revision = 'f3a1b2c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if inspector.has_table('disputes'):
        dispute_columns = {col['name'] for col in inspector.get_columns('disputes')}
        if 'description' not in dispute_columns:
            with op.batch_alter_table('disputes', schema=None) as batch_op:
                batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('section')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('delivery_status')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_tier', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('pilot_rating_sum', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pilot_rating_count', sa.Integer(), nullable=True))
        batch_op.drop_column('kyc_selfie_file')
        batch_op.drop_column('kyc_id_card_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kyc_id_card_file', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('kyc_selfie_file', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('pilot_rating_count')
        batch_op.drop_column('pilot_rating_sum')
        batch_op.drop_column('merchant_tier')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_status', sa.VARCHAR(length=20), nullable=True))

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section', sa.VARCHAR(length=50), nullable=False))

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if inspector.has_table('disputes'):
        dispute_columns = {col['name'] for col in inspector.get_columns('disputes')}
        if 'description' in dispute_columns:
            with op.batch_alter_table('disputes', schema=None) as batch_op:
                batch_op.drop_column('description')

    # ### end Alembic commands ###
